[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"
fs_permissions = [
    { access = "read", path = "./script/input/"},
    { access = "read", path = "./out/"},
    { access = "read-write", path = "./script/output/"}
]

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
sepolia = { key = "${ETHERSCAN_KEY}", chain = 11155111 }
arbitrum_one = { key = "${ARBISCAN_KEY}", chain = 42161, url = "https://api.arbiscan.io/api" }
arbitrum_one_sepolia = { key = "${ARBISCAN_KEY}", chain = 421614, url = "https://api-sepolia.arbiscan.io/api" }
